logging:
  level:
    root: INFO
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:app;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=TRUE
    username: sa
    password: ''
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0.0.0
    baseline-description: Initial
    locations: classpath:db/migration
